service: event-users-testing

frameworkVersion: 3.27.0

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/events-testing-table/index/eventid-index"


package:
  individually: true

functions:
  v1:
    handler: bin/v1
    package:
      patterns:
        - './bin/v1'
    events:
      - http:
          path: /v1
          method: GET
          request:
            parameters:
              querystrings:
                param: true