# double-booked When maintaining a calendar of events, it is important to know if an event overlaps with another event.
# Given a sequence of events, each having a start and end time, write a program that will return
# the sequence of all pairs of overlapping events.
service: create-event2

frameworkVersion: 3.27.0

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/eventstable"

package:
  individually: true

functions:
  v1:
    handler: bin/v1
    package:
      patterns:
        - './bin/v1'
    events:
      - http:
          path: /v1
          method: POST