service: create-event-testing

frameworkVersion: 3.27.0

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-1:535941052703:table/events-testing-table"

package:
  individually: true

functions:
  v1:
    handler: bin/v1
    package:
      patterns:
        - './bin/v1'
    events:
      - http:
          path: /v1
          method: POST
